"""
Created on Fri May 13 2022
@author: agerlt, rcasukhela
"""

from numpy import histogramdd
from scipy.spatial.transform import Rotation as R
from scipy.ndimage import gaussian_filter

class ODF:
    '''
    Parent ODF class.

    Dependencies:
    --------------
    import orix
    '''

# ============================ #
#          Initialize          #
# ============================ #
    def __init__(self, orientations, sigma=1, bin_number=100, method="fast"):
        '''
        Generates ODF over rotations, given orientations. Only "Fast" method is
        supported, currently.

        This ODF is being generated

        The ODF is generated by first creating a histogram with forced bin numbers.
        Second, the histogram is convolved with a Gaussian kernel with fixed variance,
        sigma.

        Inputs:
        --------------
        orientations : np.array
            This is an array of orientations, in quaternion space.

        bin_number : int
            Number of bins in one dimension (for a total of three, X, Y, and Z)
            we'd like to create the histogram over. (MUST BE NON-NEGATIVE)

        sigma : float
            Variance of the Gaussian kernel when we blur the histogram. (MUST BE
            GREATER THAN OR EQUAL TO ZERO))

        ***method*** : str
            "fast" ONLY for now, eventually "accurate". WARNING:
            Currently only "fast" (AND INACCURATE) ODF generation is supported.


        Outputs:
        --------------
        orientation_xyz : orix.quaternion.Orientation
            Transformed orientations from quaternion space to XYZ Rodriguez
            space.

        block : np.array
            This array should contain the values of the smoothed histogram
            that we want.

        bins : int
            The number of bins we used to make `block`.

        Dependencies:
        --------------
        from numpy import histogramdd
        from scipy.spatial.transform import Rotation as R
        from scipy.ndimage import gaussian_filter


        '''
        self.orientation_xyz = R.from_quat(orientations.data).as_mrp()

        hist = histogramdd(
            self.orientation_xyz,
            range = [[-1, 1], [-1, 1], [-1, 1]],
            )[0]

        self.block = gaussian_filter(hist, sigma=sigma)
        self.bins = bin_number


# ============================ #
#          Methods             #
# ============================ #

    def query(self, input_orientations):
        '''
        Returns likelihoods based on the ODF, for a given set of input
        orientations.


        Inputs:
        --------------
        input_orientations: orix.quaternion.Orientation
            Orientations we would like to query their likelihood for.


        Outputs:
        --------------
        likelihood : list
            Contains a list of likelihoods for the input orientations.


        Dependencies:
        --------------
        from scipy.spatial.transform import Rotation as R
        
        '''
        mrp_querys = R.from_quat(input_orientations.data).as_mrp()

        # NOTE: This line needs a comment to describe what it does. It is unclear.
        indices = ((((self.orientation_xyz+1)/2) * self.bins).astype('uint'))

        likelihood = [self.block[ind[0],ind[1],ind[2]] for ind in indices]

        return likelihood